apiVersion: apps/v1
kind: ReplicaSet 
metadata:
  name: nginx
spec:
  replicas: 2 
  selector:
    matchLabels: 
      app: nginx
      template: replicaset
  template:
    metadata:
      labels:
        app: nginx
        template: replicaset
    spec:
      containers:
      - name: nginx
        image: nginx:1.13-alpine 
        ports:
        - containerPort: 80

